### ISSUE TITLE
Blender generated metalicroughness is not matching with Map Merging Tool

### ISSUE THREAD

**Issue by harshilpoly9** [soadzoor/Map-Merging-Tool#2]
Hello,

We need Metalicroughness for GLTF file format. We have Metalness and Roughness as separate files. As our platform is currently generating metallicRoughness Image using your tool, but we are not sure Is it right or wrong.

We need confirmation that yes we are working on right way.

Our current generating process is as following instructions as mentioned below link has explained.

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#metallic-roughness-material

But we have confusion about our output is proper or not.

Please find attachments file includes metalness, roughness image and metallicRoughness images; one generated by our platform another generated by blender.

[MetaliRoughness Sample File.zip](https://github.com/soadzoor/Map-Merging-Tool/files/4010350/MetaliRoughness.Sample.File.zip)

**Comment by soadzoor** [comment]
Hey @harshilpoly9 ,

Seems like a channel-mismatch. The most common pairs are these:
Red: Occlusion
Green: Roughness
Blue: Metallic

This is how my tool does it, along with Unreal engine, three.js, and glTF. In blender, it seems like it's not a strict rule, you can use the channels how you want them. But you can definitely use the same assignments, just use a "Separate RGB" node like in the picture below, then connect the "G" with "Roughness", and "B" with "Metallic":
https://docs.blender.org/manual/en/2.80/_images/addons_io-gltf2_material-metalRough.png

You can read more about this topic here: https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html


I'm not sure how you created the "yellowish" image (within the "blender generate" folder), but the other one (probably created with my tool, within the "Our platform generate" folder) seems to be a valid metallic-roughness texture that you can use in a node-graph like the one above.

Let me know if that helps.

**Comment by harshilpoly9** [comment]
Thanks for your quick response. 

We tried to use Blender, but can not generate green metallicRoughness. 
I have followed steps : 
https://docs.blender.org/manual/en/2.80/_images/addons_io-gltf2_material-metalRough.png

![image_2019_12_31T09_20_28_802Z](https://user-images.githubusercontent.com/47975899/71616578-003d3700-2bdd-11ea-8c21-661904e5dfed.png)

I have also try to use photoshop, but I could not generate metalicRoughness. 

![image_2019_12_31T09_24_21_615Z](https://user-images.githubusercontent.com/47975899/71616682-82c5f680-2bdd-11ea-94a9-720eb6e14cc1.png)


May I know, any other tool which can generate same image as [your tool](https://github.com/soadzoor/Map-Merging-Tool) ?

**Comment by soadzoor** [comment]
@harshilpoly9 The node structure you sent me doesn't generate anything as far as I know. It uses an already created metallicroughness texture, where the B channel contains the metallic part, and the G channel contains the roughness part. I don't know if the image you're using is right though. If it's the one on the left handside, than it seems to be a simple diffuse texture. You shouldn't use that like this.

I don't know any other tool that can merge images like this, that's why I created it in the first place.

**Comment by soadzoor** [comment]
Since there's no new replies, I'm going to close this issue now. If you still encounter any questions related to this, feel free to open it again, or open a new one.
